import { getMinioClient, getDefaultBucket } from "./client";

/**
 * Get the public MinIO endpoint for presigned URLs
 * This is the endpoint that browsers can access (e.g., localhost or a public domain)
 */
function getPublicMinioEndpoint(): string {
  // Use MINIO_PUBLIC_ENDPOINT if set, otherwise default to localhost
  const publicEndpoint = process.env.MINIO_PUBLIC_ENDPOINT || "localhost";
  return publicEndpoint;
}

/**
 * Replace the internal MinIO endpoint with the public endpoint in a presigned URL
 * This is necessary because presigned URLs generated by MinIO use the client's endpoint,
 * which in Docker is the internal service name (e.g., "minio") that browsers can't access.
 */
function replaceEndpointInUrl(url: string): string {
  try {
    const internalEndpoint = process.env.MINIO_ENDPOINT || "minio";
    const publicEndpoint = getPublicMinioEndpoint();
    const publicPort = process.env.MINIO_PORT || "9000";
    const useSSL = process.env.MINIO_SSL === "true";
    const protocol = useSSL ? "https" : "http";

    // Parse the URL to extract components
    const urlObj = new URL(url);
    
    // Only replace if the hostname matches the internal endpoint
    if (urlObj.hostname === internalEndpoint) {
      // Replace hostname with public endpoint
      urlObj.hostname = publicEndpoint;
      // Update port if needed (preserve port from original URL if it exists)
      if (urlObj.port) {
        urlObj.port = publicPort;
      }
      return urlObj.toString();
    }

    // If hostname doesn't match, try regex replacement as fallback
    // Pattern: http://minio:9000/... -> http://localhost:9000/...
    const internalUrlPattern = new RegExp(
      `${protocol}://${internalEndpoint.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}:${publicPort}`,
      "g"
    );
    return url.replace(
      internalUrlPattern,
      `${protocol}://${publicEndpoint}:${publicPort}`
    );
  } catch (error) {
    // If URL parsing fails, fall back to regex replacement
    const internalEndpoint = process.env.MINIO_ENDPOINT || "minio";
    const publicEndpoint = getPublicMinioEndpoint();
    const publicPort = process.env.MINIO_PORT || "9000";
    const useSSL = process.env.MINIO_SSL === "true";
    const protocol = useSSL ? "https" : "http";

    const internalUrlPattern = new RegExp(
      `${protocol}://${internalEndpoint.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}:${publicPort}`,
      "g"
    );
    return url.replace(
      internalUrlPattern,
      `${protocol}://${publicEndpoint}:${publicPort}`
    );
  }
}

/**
 * Generate a presigned URL for downloading a file
 * @param storageKey - The storage key (path) of the file
 * @param expirySeconds - URL expiry time in seconds (default: 7 days)
 * @param bucket - Optional bucket name (defaults to MINIO_BUCKET env var)
 * @returns Promise that resolves to the presigned URL
 */
export async function generatePresignedUrl(
  storageKey: string,
  expirySeconds: number = 7 * 24 * 60 * 60, // 7 days
  bucket?: string
): Promise<string> {
  const client = getMinioClient();
  const bucketName = bucket || getDefaultBucket();

  const url = await client.presignedGetObject(
    bucketName,
    storageKey,
    expirySeconds
  );

  // Replace internal endpoint with public endpoint for browser access
  return replaceEndpointInUrl(url);
}

/**
 * Generate a presigned URL for uploading a file
 * @param storageKey - The storage key (path) where the file will be stored
 * @param expirySeconds - URL expiry time in seconds (default: 1 hour)
 * @param bucket - Optional bucket name (defaults to MINIO_BUCKET env var)
 * @returns Promise that resolves to the presigned URL
 */
export async function generatePresignedPutUrl(
  storageKey: string,
  expirySeconds: number = 60 * 60, // 1 hour
  bucket?: string
): Promise<string> {
  const client = getMinioClient();
  const bucketName = bucket || getDefaultBucket();

  const url = await client.presignedPutObject(
    bucketName,
    storageKey,
    expirySeconds
  );

  // Replace internal endpoint with public endpoint for browser access
  return replaceEndpointInUrl(url);
}

/**
 * Generate presigned URLs for multiple files
 * @param storageKeys - Array of storage keys (paths)
 * @param expirySeconds - URL expiry time in seconds (default: 7 days)
 * @param bucket - Optional bucket name (defaults to MINIO_BUCKET env var)
 * @returns Promise that resolves to an object mapping storage keys to URLs
 */
export async function generatePresignedUrls(
  storageKeys: string[],
  expirySeconds: number = 7 * 24 * 60 * 60, // 7 days
  bucket?: string
): Promise<Record<string, string>> {
  const urls: Record<string, string> = {};

  await Promise.all(
    storageKeys.map(async (key) => {
      urls[key] = await generatePresignedUrl(key, expirySeconds, bucket);
    })
  );

  return urls;
}

/**
 * Generate a presigned URL for server-side/internal use (no endpoint replacement).
 * Use this when the URL will be consumed by server-side code (e.g., the DICOM proxy)
 * that can reach MinIO via the internal Docker network hostname.
 * @param storageKey - The storage key (path) of the file
 * @param expirySeconds - URL expiry time in seconds (default: 12 hours)
 * @param bucket - Optional bucket name (defaults to MINIO_BUCKET env var)
 * @returns Promise that resolves to the presigned URL with the internal endpoint
 */
export async function generateInternalPresignedUrl(
  storageKey: string,
  expirySeconds: number = 12 * 60 * 60, // 12 hours
  bucket?: string
): Promise<string> {
  const client = getMinioClient();
  const bucketName = bucket || getDefaultBucket();

  // Return the raw presigned URL without replacing the endpoint.
  // The MinIO client uses the internal endpoint (e.g., "minio") which is
  // reachable from within the Docker network.
  return await client.presignedGetObject(bucketName, storageKey, expirySeconds);
}

/**
 * Generate internal presigned URLs for multiple files (no endpoint replacement).
 * @param storageKeys - Array of storage keys (paths)
 * @param expirySeconds - URL expiry time in seconds (default: 12 hours)
 * @param bucket - Optional bucket name (defaults to MINIO_BUCKET env var)
 * @returns Promise that resolves to an object mapping storage keys to URLs
 */
export async function generateInternalPresignedUrls(
  storageKeys: string[],
  expirySeconds: number = 12 * 60 * 60,
  bucket?: string
): Promise<Record<string, string>> {
  const urls: Record<string, string> = {};

  await Promise.all(
    storageKeys.map(async (key) => {
      urls[key] = await generateInternalPresignedUrl(key, expirySeconds, bucket);
    })
  );

  return urls;
}

